### ISSUE TITLE
Error in TempFileStoreWorker storage loop: StorageAdapter createWriteStream couldn't create write stream

### ISSUE THREAD

**Issue by jdesai-git** [reaction-contrib/reaction-file-collections-sa-s3#5]
Hi Loan, 

We installed the S3 adapter package and followed the instructions as given in readme file. 
But, we are facing one issue. Media file record is getting created, but throwing an error while creating file in temp store. 
Can you pls help. Thanks in Advance.
------------
Error: Error in TempFileStoreWorker storage loop: StorageAdapter createWriteStream couldn't create write stream
reaction_1  |     at TempFileStoreWorker._callee2$ (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/node/TempFileStoreWorker.js:108:19)
reaction_1  |     at tryCatch (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:62:40)
reaction_1  |     at Generator.invoke [as _invoke] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:296:22)
reaction_1  |     at Generator.prototype.(anonymous function) [as throw] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:114:21)
reaction_1  |     at step (/opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
reaction_1  |     at /opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
reaction_1  |     at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
-----------------------------------

const buildGFS = ({ name, transform }) => (
      new S3Store({
      name, // Should be provided within buildGFS
      isPublic: true,
      objectACL: "public-read",
      chunkSize: gridFSStoresChunkSize,
      collectionPrefix: "cfs_gridfs.",
      db,
      mongodb,
      async transformWrite(fileRecord) {
        // Either write your custom transformation code here, or re-use the one from the GridFSStore constructor
          if (!transform) return null;
          
        const { size, mod, format, type } = transform;

        // Need to update the content type and extension of the file info, too.
        // The new size gets set correctly automatically by FileCollections package.
        fileRecord.type(type, { store: name });
        fileRecord.extension(format, { store: name });

        // resizing image, adding mod, setting output format
        return sharp().resize(size, size)[mod]().toFormat(format);
      }
    })
  );

Thanks,
Pricenomy

**Comment by vadym-vorobel** [comment]
Hi @jdesai-git!
We are using this package in our application right now and it works well. I can try to help you if you didn't solve the issue yet 🙂 
May you tell me what version of the package you are using? And please send rest of `setUpFileCollections.js` code

**Comment by jdesai-git** [comment]
Hi @vadym-vorobel 

Thanks for your reply.

This issue has been fixed. There was some AWS S3 bucket permission issue and hence, the file was not getting created.

Thank you

**Comment by vadym-vorobel** [comment]
Got it, @jdesai-git 
You're welcome!
